name = "Fill_outliers"
uuid = "64981851-32c5-41a4-a33e-fde5a009d9bd"
authors = ["Ignasi Fernandez"]
version = "1.0.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
